---
- name: Add file to git repo
  command:
          cmd: git add install_git.yml
          chdir: /home/ansible_project

- name: Commit the changes to the git repo
  command:
          cmd: git commit -m "Initial automated commit"
          chdir: /home/ansible_project

- name: Push the changes to git remote server
  command:
          cmd: git push origin main
          chdir: /home/ansible_project
