---
- name: Install and run a web server
  hosts: all
  become: true

  vars:
          package_name: apache2

  handlers:
          - name: restart_apache_service
            sysvinit:
                    name: apache2
                    state: restarted
  pre_tasks:
          - name: Update the cache
            apt:
                    update_cache: true          
  tasks:
          - name: Install apache service in web server
            apt:
                    name: "{{package_name}}"
                    state: present

          - name: Start apache service
            sysvinit:
                    name: "{{package_name}}"
                    state: started
                    enabled: true

          - name: Copy content file to web server
            copy:
                    src: /root/index.html
                    dest: /var/www/html/httpd/
            notify: restart_apache_service
